### ISSUE TITLE
DG + MPI?

### ISSUE THREAD

**Issue by Alex-Vasile** [ngsxfem/ngsxfem#12]
I was looking at using this package, though given the size of the problems and the advective nature of the equations I would need both DG and MPI.

The table currently lists them as not working. Is the combination currently under development or has it not been considered yet?

**Comment by schruste** [comment]
Hi! 

As ngsxfem builds on ngsolve we inherited this problem. When running in  MPI mode the mesh is distributed in a non-overlapping partitioning, i.e. volume elements only appear on one node. Hence, the neighbor information for DG is missing. This is different for faces/edges/nodes which are duplicated so that CG or HDG methods work also MPI-parallel. (This limitation, btw., is only related to solving linear systems)

If you can find an HDG-formulation that would also work for your application, MPI would be possible (but typically HDG with is not that nice anymore when considered in an unfitted setting).

Currently there is no development on the NGSolve-side afaik.

I will close this issue as it is rather an "upstream" issue of NGSolve.

Best,
Christoph

**Comment by Alex-Vasile** [comment]
Hi Christoph,

Thanks for the quick reply.

I understand all of it except this part:
> (but typically HDG with is not that nice anymore when considered in an unfitted setting).

Could you please try to explain what you mean.

Alex

**Comment by Alex-Vasile** [comment]
I have not yet tried it myself, but based on [this page](https://docu.ngsolve.org/latest/how_to/howto_parallel.html#distributed-memory) it appears that support is available. Conditional on whatever "apply operator" means.

**Comment by schruste** [comment]
Hi, 

OK, I will try to give you the idea. Not sure how easy it is to grasp it from my explanation though:

The idea of HDG is to add unknown functions on the facets of elements and to condense out the interior unknowns by static condensation (a.k.a. local solvers). This works nicely for fitted configurations for essentially all problems, allowing to transfer every DG method into a HDG variant. If your problem is nice enough and static condensation is applicable (most problems are nice in that regard) you are left with a linear systems for the unknowns living only on the facets.

Now let's come to unfitted discretizations. Here, originally a stable DG discretization is the problem. Because of possibly arbitrary bad cuts you typically add a stabilization technique. This is either something like a cell merging / aggregation technique or a ghost penalty stabilization. Both couple all volume dofs of neighboring elements together. This nicely fits the DG, but does not fit the HDG setting. Hybridization does not work anymore with the usual set of unknowns as the ghost penalty coupling really needs the volume information. 
You can remove the stabilization (and replace it with something suitable for HDG) if you only consider low order discretizations or consider surface PDEs or hope for regular cuts, but in most cases you need it.

Best,
Christoph

**Comment by schruste** [comment]
> I have not yet tried it myself, but based on [this page](https://docu.ngsolve.org/latest/how_to/howto_parallel.html#distributed-memory) it appears that support is available. Conditional on whatever "apply operator" means.

"apply operator" means that you can evaluate DG operators as needed for explicit time stepping. But solving linear systems is not possible.

**Comment by Alex-Vasile** [comment]
Thank you for the replies!
