### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by LavrovaO** [ngsxfem/ngsxfem#6]
Hello, 

While running cutfem.ipynb through the docker the error with dCut (NameError: name 'dCut' is not defined) appears. I use

docker run -p 8888:8888 ngsxfem/ngsxfem-jupyter

How could this issue be overcomed?

Olga

**Comment by schruste** [comment]
Dear Olga,

thanks for the report. The problem is "only" that I forgot to rebuild the Docker-image for ngsxfem/ngsxfem-jupyter so that the one that is pulled is old. I just triggered a rebuild so that the Docker image should be updated in a few moments and then it should work again. Sorry that we overlooked this part. I guess we only updated the v2.0-branch w.r.t. to the Docker image, i.e. 
```
docker run -p 8888:8888 ngsxfem/ngsxfem-jupyter:v2.0
```
should be fine. Now, also the standard call should work though.

Best and thanks again for the report,
Christoph

**Comment by LavrovaO** [comment]
Dear Christoph, 

the Docker image ngsxfem/ngsxfem-jupyter:v2.0 works well. 

Thank you a lot for the quick response, 
Olga

**Comment by schruste** [comment]
Dear Olga,

The Docker image ngsxfem/ngsxfem-jupyter, i.e. ngsxfem/ngsxfem-jupyter:latest should also work again (make sure that a local copy of the image is updated).

Best,
Christoph

**Comment by LavrovaO** [comment]
Dear Christoph, 

You are right, the Docker image ngsxfem/ngsxfem-jupyter:latest works well after updating. 

Thanks a lot for your efforts to solve the issue.

Kind regards, 
Olga
